Repository nearby-sharing/android, pull requests merged in 2024-04, with the labels that each got.

#142 Cross-Platform Compilation
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  lib/ShortDev.Microsoft.ConnectedDevices/Serialization/ValueSet.Schema.cs
  lib/ShortDev.Microsoft.ConnectedDevices/Serialization/ValueSet.bond.txt
Labels: type::feature-request, area::Receive, area::Send

#149 Prevent IME suggestions for the Bluetooth MAC address input
  CREDITS.md
  src/Resources/layout/activity_mac_address.xml
Labels: type::feature-request, area::UI-UX

#152 Observe exceptions of task after timeout
  lib/ShortDev.Microsoft.ConnectedDevices/Extensions.cs
  lib/ShortDev.Microsoft.ConnectedDevices/Transports/ICdpTransport.cs
  tests/ShortDev.Microsoft.ConnectedDevices.Test/UtilsTest.cs
Labels: type::bug, area::libCdp

#153 Updated Spanish and add Catalan translations
  src/Assets/ca/MacAddressInfo.html
  src/Assets/ca/Welcome.html
  src/Resources/values-ca/strings.xml
  src/Resources/values-es/strings.xml
Labels: type::feature-request, area::UI-UX, area::translation
